### ISSUE TITLE
Crash When click the  Music consumption Examples?

### ISSUE THREAD

**Issue by tracyliu1** [googlesamples/leanback-showcase#17]
![image](https://cloud.githubusercontent.com/assets/17140629/19349882/fd96881e-9187-11e6-95a9-4c7a970de2bb.png)

The code is well done on other computer, but  When i run  on my computer (Music consumption Examples), it crashed .
The only difference is my buildToolsVersion  is  24.0.2 ,I will check the jdk version ,or change the buildToolsVersion , check later.

Sorry for my English

**Comment by tracyliu1** [comment]
I haven`t change the buildToolsVersion,  it still not works

**Comment by keyvanamiri** [comment]
Which device and Android version are you running this app on? I'm guessing you're installing it on a Pre-L device (API level below 21). The inflating issue you're getting should be related to some animator APIs that were introduced in API 21. Those APIs are now made compatible for MediaNowPlayingView, and you shouldn't be seeing this issue in the new support library release.

**Comment by dhaval0122** [comment]
not working with sony bravia Android(5.1.1) TV. any solution? 


    Process: com.djandroid.jdroid.aarti, PID: 2676
                                                                              android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v17.leanback.widget.MediaNowPlayingView
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                  at android.support.v17.leanback.widget.AbstractMediaItemPresenter$ViewHolder.<init>(AbstractMediaItemPresenter.java:207)
                                                                                  at android.support.v17.leanback.widget.AbstractMediaItemPresenter.createRowViewHolder(AbstractMediaItemPresenter.java:431)
                                                                                  at android.support.v17.leanback.widget.RowPresenter.onCreateViewHolder(RowPresenter.java:310)
                                                                                  at android.support.v17.leanback.widget.ItemBridgeAdapter.onCreateViewHolder(ItemBridgeAdapter.java:315)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6073)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5243)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5153)
                                                                                  at android.support.v17.leanback.widget.GridLayoutManager.getViewForPosition(GridLayoutManager.java:971)
                                                                                  at android.support.v17.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1464)
                                                                                  at android.support.v17.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:111)
                                                                                  at android.support.v17.leanback.widget.Grid.appendVisibleItems(Grid.java:371)
                                                                                  at android.support.v17.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1702)
                                                                                  at android.support.v17.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:1910)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3183)
                                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
                                                                                  at android.view.View.layout(View.java:15671)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                  at android.view.View.layout(View.java:15671)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                  at android.view.View.layout(View.java:15671)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                  at android.view.View.layout(View.java:15671)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                  at android.view.View.layout(View.java:15671)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                                  at android.view.View.layout(View.java:15671)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                  at android.view.View.layout(View.java:15671)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                  at android.view.View.layout(View.java:15671)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                  at android.view.View.layout(View.java:15671)
                                                                              	at android.view.ViewGroup.layout(ViewGroup.java:50

**Comment by dakegu** [comment]
The sample app works on TV emulator API 22.

you need post a more logs after that about what is causing inflating error for MediaNowPlayingView.
Is it being obfuscated by proguard, can you do a dexdump see if the class is in your apk?

**Comment by dakegu** [comment]
I believe the sample was fixed to work with lower platform (API level <21), feel free to reopen it if it's not.
