### ISSUE TITLE
Crash in leanback BrowseFragment

### ISSUE THREAD

**Issue by ifyousleep** [googlesamples/leanback-showcase#54]
I have this strange crash happening in leanback BrowseFragment. It occurs when fast scrolling through the row. Do you have any idea how to prevent this crash ?
```
java.lang.IllegalArgumentException: View android.support.v17.leanback.widget.ShadowOverlayContainer{cee235a V.ED..... ........ 1854,334-2268,851} is not a direct child of android.support.v17.leanback.widget.HorizontalGridView{81dc26e VFE...... ........ 0,0-1920,605 #7f12014c app:id/row_content}
                                                   at android.support.v7.widget.RecyclerView.getChildViewHolder(SourceFile:4224)
                                                   at android.support.v17.leanback.widget.GridLayoutManager$3.createItem(SourceFile:1488)
                                                   at ct.a(SourceFile:78)
                                                   at android.support.v17.leanback.widget.Grid.j(SourceFile:346)
                                                   at android.support.v17.leanback.widget.GridLayoutManager.m(SourceFile:1734)
                                                   at android.support.v17.leanback.widget.GridLayoutManager.j(SourceFile:2070)
                                                   at android.support.v17.leanback.widget.GridLayoutManager.scrollHorizontallyBy(SourceFile:2005)
                                                   at android.support.v7.widget.RecyclerView$d.run(SourceFile:4722)
                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                   at android.view.Choreographer.doFrame(Choreographer.java:616)
                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                   at android.os.Looper.loop(Looper.java:154)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6120)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by manabernetes** [comment]
It happened to me too.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
